{% set name = "asttokens" %}
{% set version = "1.1.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "55c00658f9e0fa7e031529c719e8bb2cdbad0ad973aaff08faf6bfdaa96ca4ed"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six

test:
  imports:
    - asttokens

about:
  home: "https://github.com/gristlabs/asttokens"
  license: "Apache 2.0"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "Annotate AST trees with source code positions"

extra:
  recipe-maintainers:
    - CJ-Wright
