{% set name = "srreal" %}
{% set version = "v1.2" %}
{% set sha256 = "d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win or py2k]

requirements:
  build:
    - python
    - setuptools
    - numpy 1.11.*
    - libdiffpy >=1.3.4,1.3.*
    - pycifrw
    - diffpy.structure
  run:
    - python
    - setuptools
    - numpy >=1.11.2
    - libdiffpy >=1.3.4,1.3.*
    - pycifrw
    - diffpy.structure
    - pyobjcryst >=2.0*
    - periodictable

test:
  imports:
    - diffpy
    - diffpy.srreal
    - diffpy.srreal.tests

about:
  home: https://github.com/diffpy/diffpy.srreal
  summary: Calculators for PDF, bond valence sum and other
    pair-interaction quantities.
  license: Modified BSD License
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CJ-Wright
