{% set name = "inquirer" %}
{% set version = "2.6.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "5f6e5dcbc881f43554b6fdfea245e417c6ed05c930cdb6e09b5df7357c288e06"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - blessings ==1.7
    - pip
    - python
    - python-editor ==1.0.4
    - readchar ==2.0.1
  run:
    - blessings ==1.7
    - python
    - python-editor ==1.0.4
    - readchar ==2.0.1

test:
  imports:
    - inquirer
    - inquirer.render
    - inquirer.render.console

about:
  home: "https://github.com/magmax/python-inquirer"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Collection of common interactive command line user interfaces, based on Inquirer.js"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
