{% set name = "dataframe_sql" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57aff338021269b4c770d7bd6166544595ffc2f31a13f3eed2519c53a21e7e9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sql-to-ibis

test:
  imports:
    - dataframe_sql
    - dataframe_sql.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zbrookle/dataframe_sql
  summary: A package for querying dataframes using SQL
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - CJ-Wright
