{% set name = "snoop" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "562e81d6f03dc418779d758738e599d9a0950ae347c11b98b8c4467e422fd3ae"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - asttokens
    - cheap_repr >=0.4.0
    - executing
    - pygments
    - python
    - six

test:
  imports:
    - snoop
  requires:
    - birdseye
    - django
    - littleutils
    - numpy >=1.16.3
    - pandas >=0.24.2
    - pytest

about:
  home: "http://github.com/alexmojaki/snoop"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Powerful debugging tools for Python"

extra:
  recipe-maintainers:
    - CJ-Wright
