{% set name = "intake-sql" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/intake/intake-sql/archive/{{ version }}.tar.gz
  sha256: 8bd3866c1f70e2d655994880e63db95c9ee7f7875d358e544b842168c231e222

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - intake
    - pandas
    - python
    - sqlalchemy

test:
  imports:
    - intake_sql

about:
  home: "https://github.com/ContinuumIO/intake-sql"
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "SQL plugin for Intake"
  dev_url: https://github.com/intake/intake-sql

extra:
  recipe-maintainers:
    - CJ-Wright
