{% set name = "ibm-db-sa" %}
{% set version = "0.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 6e87b3ff98ff9444465ca0f0a97e484baf78986eddf7b2f47a2a80581a8b6d37

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - ibm_db >=2.0.0
    - python
    - setuptools
    - sqlalchemy >=0.7.3

test:
  imports:
    - ibm_db_sa
  requires:
    - nose >=0.11

about:
  home: "http://pypi.python.org/pypi/ibm_db_sa/"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "SQLAlchemy support for IBM Data Servers"
  dev_url: "https://github.com/ibmdb/python-ibmdbsa"

extra:
  recipe-maintainers:
    - CJ-Wright
