{% set version = "R3.14.12.4" %}

package:
    name: epics-base
    version: {{ version }}

source:
    fn: base{{ version }}.tar.gz
    url: http://www.aps.anl.gov/epics/download/base/baseR{{ version }}.tar.gz
    sha256: 0ea4a74e83ff73d68b64de89bedf7c42102edc2cc69c69fd49eb35c04dc9e3de
    patches:
        - config_site.diff [not win]
        - config_common.diff [not win]
        - config_readline.diff [linux]
        - bind-returns-eacces.patch

build:
  number: 0

requirements:
  build:
    - m2w64-make [win]
    - perl [win]
    - patch [win]

test:
  commands:
    - caget -h
    - caput -h
    - camonitor -h
    - softIoc -h

about:
    home: http://www.aps.anl.gov/epics
    license: Epics Open License
    summary: EPICS Base Library

extra:
  recipe-maintainers:
    - CJ-Wright
