{% set name = "vagrant" %}
{% set version = "2.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0a228f5185b24b72efcc5a3924f86fa9fabab6f7562c3c63c1d9d239aa72a7b1

build:
  number: 0
  script: bundle install

requirements:
  host:
    - ruby >=2.2
  run:
    - ruby

test:
  commands:
    - vagrant --help

about:
  home: http://github.com/hashicorp/vagrant
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Vagrant is a tool for building and distributing development environments.'

extra:
  recipe-maintainers:
    - CJ-Wright
