{% set name = "sql-to-ibis" %}
{% set version = "0.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 447626d04839de3549f25b00428823e600636047a64bb2e224b80bbbb12fa920

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ibis-framework ==1.3.0
    - lark-parser ==0.8.5
    - python >=3.6

test:
  imports:
    - sql_to_ibis
    - sql_to_ibis.conversions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zbrookle/sql_to_ibis
  summary: A package for converting sql into ibis expressions
  license_file: LICENSE.txt
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - CJ-Wright
    - mariusvniekerk
